### GET - Tüm telemetry kayıtlarını getir
GET http://localhost:8080/telemetry
Accept: application/json

### GET - Belirli telemetry kaydı (örnek: id=1)
GET http://localhost:8080/telemetry/1
Accept: application/json

### POST - Yeni telemetry kaydı ekle
POST http://localhost:8080/telemetry
Content-Type: application/json

{
  "latitude": 45.123456,
  "longitude": 120.654321,
  "altitude": 4321,
  "speed": 87.34,
  "battery": 92
}

### Random Telemetry POST
POST http://localhost:8080/telemetry/random
Content-Type: application/json


### DELETE - Telemetry kaydını sil (örnek: id=1)
DELETE http://localhost:8080/telemetry/1

### Tüm Telemetry kayıtlarını sil
DELETE http://localhost:8080/telemetry/all
