### Tüm telemetri kayıtları
GET http://localhost:8080/api/telemetry
Accept: application/json

### Belirli telemetri kaydet
GET http://localhost:8080/api/telemetry/1
Accept: application/json

### Yeni telemetri kaydet
POST http://localhost:8080/api/telemetry
Content-Type: application/json

{
  "currentLatitude": 40.0,
  "currentLongitude": 40.0,
  "altitude": 4321,
  "speed": 80,
  "battery": 80
}

### Random telemetri kaydet
POST http://localhost:8080/api/telemetry/random
Content-Type: application/json

### Telemetri kaydını sil
DELETE http://localhost:8080/api/telemetry/1

### Tüm telemetri kayıtlarını sil
DELETE http://localhost:8080/api/telemetry/all

### Telemetri hedef koordinatları güncelle
PUT http://localhost:8080/api/telemetry/1/destination?targetLatitude=36.363636&targetLongitude=26.262626

### Telemetriyi hedefe doğru hareket ettir
PUT http://localhost:8080/api/telemetry/1/move

### İHA başlat
PUT http://localhost:8080/api/telemetry/1/start

### Hangi İHA aktif?
GET http://localhost:8080/api/telemetry/active

### Uçuşu durdur
PUT http://localhost:8080/api/telemetry/stop


